### ISSUE TITLE
大佬,这个最新版的,能不能添加DOMAIN、DOMAIN-SUFFIX、DOMAIN-MATCH，IP-CIDR，GEOIP 这些规则

### ISSUE THREAD

**Issue by 17674136685** [arror/Mango#35]
想用GEOIP给定地理区域内的 IP (使用 Country Code 指定) 设置使用代理

**Comment by arror** [comment]
> 想用GEOIP给定地理区域内的 IP (使用 Country Code 指定) 设置使用代理

只支持 xray 支持的匹配规则。
