### ISSUE TITLE
Flutter app base on Mango code

### ISSUE THREAD

**Issue by mortezaom** [arror/Mango#37]
Hi,
As I saw the source code, I am so excited to create a flutter app and use the Mango codebase as the iOS implementation. I want to know which classes and files are needed to connect to the VPN also is there any documentation about how to create config json and pass them to the connect method for connecting?

**Comment by arror** [comment]
Shared文件夹下的文件用于构建xray的配置文件 & MGPacketTunnelManager.swift用于启动VPN。
