### ISSUE TITLE
暂不支持Trojan协议解析

### ISSUE THREAD

**Issue by NasserGo** [arror/Mango#38]
iOS 16
DEVELOPMENT_TEAM、APP_ID 已修改

方式1：通过扫描二维码添加Trojan
弹窗提示：暂不支持Trojan协议解析

方式2：手动添加Trojan协议
弹窗提示：
infra/conf/serial: failed to parse json config
infra/conf: Trojan server address is not set.
（反复检查，确认Description、Address、Prot、Password、Email）均有填写。

**Comment by houmie** [comment]
我遇到了与Trojan相同的问题。

此外，我也在使用Shadowsocks+gRPC+TLS时遇到了完全相同的错误报告。

请问何时能支持Trojan和Shadowsocks

@arror

**Comment by arror** [comment]
扫码不支持 trojan 和 shadowsocks，手动添加的方式，请自行 debug 最后生成的配置是否符合预期吧。

**Comment by houmie** [comment]
@arror 

No, this is not just an issue with scanning.  I have tried adding it manually (without scanning) but it fails too.

The error is:
infra/conf/serial: failed to parse json config
infra/conf: Trojan server address is not set.

This only happens with Trojan or Shadowsocks+gRPC+TLS

Where would I see the exact error? Mango only shows the error above.

**Comment by whatbugsyou** [comment]
[this would help](https://github.com/arror/Mango/pull/46)

**Comment by houmie** [comment]
Thank you @whatbugsyou 
I have merged your PR into my fork. I will test this and report back.
I'm really happy that you fixed it.
