### ISSUE TITLE
几分钟会断连问题

### ISSUE THREAD

**Issue by lfpak** [arror/Mango#40]
ios 15.4.1 iphone7，gogle 搜索my ip adress ，去访问几个网站后就会断开连接

用的是xraykit 0.1.47

**Comment by arror** [comment]
请确认使用 xray core binary 会不会有同样的问题呢？

**Comment by lfpak** [comment]
> 请确认使用 xray core binary 会不会有同样的问题呢？

xray core binary 是在哪里下载啊？

**Comment by arror** [comment]
> > 请确认使用 xray core binary 会不会有同样的问题呢？
> 
> xray core binary 是在哪里下载啊？

https://github.com/XTLS/Xray-core/releases

**Comment by lfpak** [comment]
> > > 请确认使用 xray core binary 会不会有同样的问题呢？
> > 
> > 
> > xray core 二进制文件在哪里下载啊？
> 
> https://github.com/XTLS/Xray-core/releases

还是不太懂如何操作，是否能留个邮箱或者其它联系方式付费咨询？
