### ISSUE TITLE
如何将Xray-Core更新到1.8.3版本？

### ISSUE THREAD

**Issue by houmie** [arror/Mango#41]
你好，老板，
请问更新Xray-core的最佳方式是什么？

我尝试了更新依赖项，这些是可以的：
Tun2SocksKit从2.2.0更新到2.4.0
XrayKit从0.1.45更新到0.1.47

但是，如果我想将XrayKit更新到最新的0.1.79版本，它则无法构建。

您有什么建议吗？

**Comment by arror** [comment]
Try 0.1.80

**Comment by m1faridi** [comment]
after update to 0.1.80
 error in XrayTunnel 
Undefined symbols:
Linker command failed with exit code 1 (use -v to see invocation)
