### ISSUE TITLE
ios return 0 after stop ( freeze thread until not stopped)

### ISSUE THREAD

**Issue by tozik** [arror/Mango#54]
Hi @arror 

i can't solve one issue, i want to track on user side in NEPacketTunnelProvider spended traffic with packetFlow.
But i can't do that cause packetFlow, don't return result, possibly cause when i call Socks5Tunnel.run(withConfig: path) the method is stay freeze (but tunnel is running). 0 returning just when tunnel is stopping.

here [is](https://github.com/arror/Mango/issues/44) i've asked you, why you use  
`    override func startTunnel(options: [String : NSObject]?) async throws {
`vs
`override startTunnel(options: [String : NSObject]? = nil, completionHandler: @escaping (Error?) -> Void)
`
cause with second one, extension is not running tunnel, but maybe i'm doing something wrong

**Comment by arror** [comment]
> Hi @arror
> 
> i can't solve one issue, i want to track on user side in NEPacketTunnelProvider spended traffic with packetFlow. But i can't do that cause packetFlow, don't return result, possibly cause when i call Socks5Tunnel.run(withConfig: path) the method is stay freeze (but tunnel is running). 0 returning just when tunnel is stopping.
> 
> here [is](https://github.com/arror/Mango/issues/44) i've asked you, why you use ` override func startTunnel(options: [String : NSObject]?) async throws {`vs `override startTunnel(options: [String : NSObject]? = nil, completionHandler: @escaping (Error?) -> Void) ` cause with second one, extension is not running tunnel, but maybe i'm doing something wrong

Scocks5Tunnel 运行成功会阻塞当前线程，同时会通过 fd 读写数据，所以使用 packetFlow 将不会返回任何结果（我不是很确定，因为没验证过）。如果你想统计流量，可以修改 Socks5Tunnel 的实现，在这个位置 https://github.com/heiher/hev-socks5-tunnel/blob/master/src/hev-tunnel-macos.h 实现你的逻辑，但是这样会丢失一些其他的信息，例如流量来自哪里。希望对你有所帮助。
